services:
  wizarr:
    container_name: wizarr
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 5690:5690
    volumes:
      - /HomeBase/Docker/AppData/Config/Wizarr/:/data
      # Optional: Mount your local app for live development
      # - ./app:/app/app
    environment:
      - PUID=1000
      - PGID=1000
      - DISABLE_BUILTIN_AUTH=false
      - TZ=America/Los_Angeles
    restart: unless-stopped